// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvYiUwwgU1_ZxN9bS7nYMNwIE9GBgiK2g',
    appId: '1:429178036060:web:1df4df58e6e0479946ab99',
    messagingSenderId: '429178036060',
    projectId: 'libraryapp-efee6',
    authDomain: 'libraryapp-efee6.firebaseapp.com',
    storageBucket: 'libraryapp-efee6.firebasestorage.app',
    measurementId: 'G-V48HNR3GZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jUO0MyaADVMdl_17gvXNBQ8waD-v2no',
    appId: '1:429178036060:android:0c9b2ff167a85e8c46ab99',
    messagingSenderId: '429178036060',
    projectId: 'libraryapp-efee6',
    storageBucket: 'libraryapp-efee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAt-ke6CqTPg6ROXFxgGT_NEWKPzXOns',
    appId: '1:429178036060:ios:c88d09a98007ffbf46ab99',
    messagingSenderId: '429178036060',
    projectId: 'libraryapp-efee6',
    storageBucket: 'libraryapp-efee6.firebasestorage.app',
    iosBundleId: 'com.example.lib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAt-ke6CqTPg6ROXFxgGT_NEWKPzXOns',
    appId: '1:429178036060:ios:c88d09a98007ffbf46ab99',
    messagingSenderId: '429178036060',
    projectId: 'libraryapp-efee6',
    storageBucket: 'libraryapp-efee6.firebasestorage.app',
    iosBundleId: 'com.example.lib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvYiUwwgU1_ZxN9bS7nYMNwIE9GBgiK2g',
    appId: '1:429178036060:web:906fe5e3a4aba1a346ab99',
    messagingSenderId: '429178036060',
    projectId: 'libraryapp-efee6',
    authDomain: 'libraryapp-efee6.firebaseapp.com',
    storageBucket: 'libraryapp-efee6.firebasestorage.app',
    measurementId: 'G-5BQ3H2SZ3Q',
  );
}
